### ISSUE TITLE
The latest release doesn't have the built in tests for webhook history

### ISSUE THREAD

**Issue by DanielWJudge** [actigraph/CentrePointWebAPIDemo#3]
I want to just download the testing tool and run a test for the webhook history API call. It's not in the latest release. Instead, I have to clone the repo and build it separately.

In the future, whenever we add new calls, we should make a new release

**Comment by blitzxion** [comment]
Agreed. I'll fix this up soon.

**Comment by blitzxion** [comment]
Premature close!
Link to latest release (as of this case):
https://github.com/actigraph/CentrePointWebAPIDemo/releases/tag/1.3.1
